language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
branches:
  except:
    - v0.5
    - v0.6
    - php5.2_backport
    - documentation
services: redis-server
install: make travis-install
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - make travis-run
script:
  - vendor/bin/phpunit -c phpunit.xml.travisci
  - vendor/bin/phpunit -c phpunit.xml.cluster.travisci
after_script:
  - make stop
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
